SELECT COUNT(*)
FROM PRODUTO p
JOIN SECAO s ON p.SECCOD = s.SECCOD
JOIN GRUPO g ON p.GRPCOD = g.GRPCOD
JOIN SUBGRUPO sb ON p.SBGCOD = sb.SBGCOD
JOIN MARCA m ON p.MARCOD = m.MARCOD
JOIN REFERENCIA r ON p.PROCOD = r.PROCOD
LEFT JOIN REFERENCIA_FABRICANTE rf ON r.REFPLU = rf.REFPLU
WHERE s.SECCOD = g.SECCOD
    AND sb.GRPCOD = g.GRPCOD
    AND sb.SECCOD = s.SECCOD
    AND (:secao IS NULL OR s.SECDES LIKE %:secao%)
    AND (:grupo IS NULL OR g.GRPDES LIKE %:grupo%)
    AND (:marca IS NULL OR m.MARDES LIKE %:marca%)
    AND (:descricao IS NULL OR p.PRODES LIKE %:descricao%)
