# Adicionar ao application.yml da Business API
spring:
  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
