server:
  port: 8087
  servlet:
    context-path: /api/legacy

spring:
  application:
    name: Legacy API (Test Mode)
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
  main:
    lazy-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    db:
      enabled: false

logging:
  level:
    com.sysconard.legacy: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
