server:
  port: 8087
  servlet:
    context-path: /api/legacy

spring:
  application:
    name: Legacy API (Read-Only)
  datasource:
    url: jdbc:sqlserver://45.174.189.210:1433;databaseName=SysacME;encrypt=false;trustServerCertificate=true;integratedSecurity=false;sslProtocol=TLS;loginTimeout=30;connectionTimeout=30;readOnly=true
    username: sa
    password: '@fcm123'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 1
      minimum-idle: 0
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      initialization-fail-timeout: -1
      validation-timeout: 3000
      leak-detection-threshold: 60000
      pool-name: LegacyHikariPool
      auto-commit: false
      read-only: true
      validation-interval: 5000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        temp.use_jdbc_metadata_defaults: false
        connection.isolation: 2
        jdbc.batch_size: 1
        order_inserts: false
        order_updates: false
        batch_versioned_data: false
        connection.provider_disables_autocommit: true
        # Configurações de somente leitura
        hibernate.connection.autocommit: false
  main:
    lazy-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    db:
      enabled: false

logging:
  level:
    com.sysconard.legacy: INFO
    com.sysconard.legacy.config.ReadOnlyInterceptor: INFO
    com.sysconard.legacy.config.HttpErrorHandler: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    com.zaxxer.hikari: WARN
    # Suprimir logs de parsing HTTP específicos
    org.apache.coyote.http11.Http11Processor: WARN
    org.apache.coyote.http11.Http11InputBuffer: WARN
    org.apache.coyote.http11: WARN
    # Log de operações de escrita para auditoria
    org.hibernate.engine.jdbc.batch: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" 
